# Generated by Django 3.0.8 on 2021-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='image6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
