# Generated by Django 3.2.2 on 2021-05-08 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_input_image6'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='t_model',
            field=models.CharField(choices=[('1', 'Model1'), ('2', 'Model2'), ('3', 'Model3')], default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
